// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using War.Infrastructure.Persistence;

#nullable disable

namespace War.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WarDbContext))]
    [Migration("20260312211435_InitialCharacterSnapshotFlow")]
    partial class InitialCharacterSnapshotFlow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("War.Infrastructure.Persistence.CharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("class_type");

                    b.Property<decimal>("CurrentHp")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_hp");

                    b.Property<decimal>("CurrentMana")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_mana");

                    b.Property<long>("CurrentXp")
                        .HasColumnType("bigint")
                        .HasColumnName("current_xp");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<long>("TotalXp")
                        .HasColumnType("bigint")
                        .HasColumnName("total_xp");

                    b.Property<decimal>("UltimateCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ultimate_charge");

                    b.Property<long>("XpToNextLevel")
                        .HasColumnType("bigint")
                        .HasColumnName("xp_to_next_level");

                    b.HasKey("Id");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("War.Infrastructure.Persistence.CharacterSkillProgressEntity", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("SkillId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("skill_id");

                    b.Property<int>("CurrentAscensionLevel")
                        .HasColumnType("integer")
                        .HasColumnName("current_ascension_level");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unlocked");

                    b.Property<int?>("UnlockedAtCharacterLevel")
                        .HasColumnType("integer")
                        .HasColumnName("unlocked_at_character_level");

                    b.HasKey("CharacterId", "SkillId");

                    b.ToTable("character_skill_progress", (string)null);
                });

            modelBuilder.Entity("War.Infrastructure.Persistence.CharacterSkillProgressEntity", b =>
                {
                    b.HasOne("War.Infrastructure.Persistence.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
