// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using War.Infrastructure.Persistence;

#nullable disable

namespace War.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WarDbContext))]
    partial class WarDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("War.Infrastructure.Persistence.AdminSkillRecordEntity", b =>
                {
                    b.Property<Guid>("RecordId")
                        .HasColumnType("uuid")
                        .HasColumnName("record_id");

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("class_type");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at_utc");

                    b.Property<string>("DefinitionJson")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("definition_json");

                    b.Property<DateTimeOffset?>("DeletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deleted_at_utc");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<int>("DraftVersion")
                        .HasColumnType("integer")
                        .HasColumnName("draft_version");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("boolean")
                        .HasColumnName("is_deleted");

                    b.Property<bool>("IsUltimate")
                        .HasColumnType("boolean")
                        .HasColumnName("is_ultimate");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("origin");

                    b.Property<DateTimeOffset?>("PublishedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at_utc");

                    b.Property<string>("PublishedBy")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("published_by");

                    b.Property<string>("PublishedDefinitionJson")
                        .HasColumnType("text")
                        .HasColumnName("published_definition_json");

                    b.Property<int?>("PublishedVersion")
                        .HasColumnType("integer")
                        .HasColumnName("published_version");

                    b.Property<string>("SkillId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("skill_id");

                    b.Property<string>("Slot")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("slot");

                    b.Property<int>("UnlockLevel")
                        .HasColumnType("integer")
                        .HasColumnName("unlock_level");

                    b.Property<DateTimeOffset>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at_utc");

                    b.HasKey("RecordId");

                    b.HasIndex("SkillId")
                        .IsUnique();

                    b.HasIndex("ClassType", "IsDeleted");

                    b.HasIndex("IsDeleted", "PublishedVersion");

                    b.ToTable("admin_skill_records", (string)null);
                });

            modelBuilder.Entity("War.Infrastructure.Persistence.CharacterEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ClassType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("class_type");

                    b.Property<decimal>("CurrentHp")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_hp");

                    b.Property<decimal>("CurrentMana")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("current_mana");

                    b.Property<long>("CurrentXp")
                        .HasColumnType("bigint")
                        .HasColumnName("current_xp");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("gender");

                    b.Property<DateTimeOffset?>("LastBasicComboCompletedAtUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_basic_combo_completed_at_utc");

                    b.Property<int>("LastBasicComboStage")
                        .HasColumnType("integer")
                        .HasColumnName("last_basic_combo_stage");

                    b.Property<int>("Level")
                        .HasColumnType("integer")
                        .HasColumnName("level");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<long>("TotalXp")
                        .HasColumnType("bigint")
                        .HasColumnName("total_xp");

                    b.Property<decimal>("UltimateCharge")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("ultimate_charge");

                    b.Property<long>("XpToNextLevel")
                        .HasColumnType("bigint")
                        .HasColumnName("xp_to_next_level");

                    b.HasKey("Id");

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("War.Infrastructure.Persistence.CharacterSkillProgressEntity", b =>
                {
                    b.Property<Guid>("CharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("character_id");

                    b.Property<string>("SkillId")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("skill_id");

                    b.Property<int>("CurrentAscensionLevel")
                        .HasColumnType("integer")
                        .HasColumnName("current_ascension_level");

                    b.Property<bool>("IsUnlocked")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unlocked");

                    b.Property<int?>("UnlockedAtCharacterLevel")
                        .HasColumnType("integer")
                        .HasColumnName("unlocked_at_character_level");

                    b.HasKey("CharacterId", "SkillId");

                    b.ToTable("character_skill_progress", (string)null);
                });

            modelBuilder.Entity("War.Infrastructure.Persistence.CharacterSkillProgressEntity", b =>
                {
                    b.HasOne("War.Infrastructure.Persistence.CharacterEntity", null)
                        .WithMany()
                        .HasForeignKey("CharacterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
