// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBs-Xv-1cYPKrhilOj3kAwm2Cm-5zzh4oU',
    appId: '1:851938750989:web:7c1a196c22a250dfa39b44',
    messagingSenderId: '851938750989',
    projectId: 'un-proyecto-13d67',
    authDomain: 'un-proyecto-13d67.firebaseapp.com',
    storageBucket: 'un-proyecto-13d67.firebasestorage.app',
    measurementId: 'G-93XJJBT7MV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6bWoeFEXZu8e4tpGzsTAarcOsyUaL75Y',
    appId: '1:851938750989:android:6f958c4315b2f245a39b44',
    messagingSenderId: '851938750989',
    projectId: 'un-proyecto-13d67',
    storageBucket: 'un-proyecto-13d67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmpsVOZNkRtT_NPDZp17FBqxZdol8ljeI',
    appId: '1:851938750989:ios:9f33450f108a4275a39b44',
    messagingSenderId: '851938750989',
    projectId: 'un-proyecto-13d67',
    storageBucket: 'un-proyecto-13d67.firebasestorage.app',
    iosBundleId: 'com.example.frontendWar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmpsVOZNkRtT_NPDZp17FBqxZdol8ljeI',
    appId: '1:851938750989:ios:9f33450f108a4275a39b44',
    messagingSenderId: '851938750989',
    projectId: 'un-proyecto-13d67',
    storageBucket: 'un-proyecto-13d67.firebasestorage.app',
    iosBundleId: 'com.example.frontendWar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBs-Xv-1cYPKrhilOj3kAwm2Cm-5zzh4oU',
    appId: '1:851938750989:web:c6741f61d2a19f9fa39b44',
    messagingSenderId: '851938750989',
    projectId: 'un-proyecto-13d67',
    authDomain: 'un-proyecto-13d67.firebaseapp.com',
    storageBucket: 'un-proyecto-13d67.firebasestorage.app',
    measurementId: 'G-SL2290VNT1',
  );
}
